export const TRANSLATION_LANGUAGES = ['punjabi', 'english', 'spanish', 'hindi'];
export const ENGLISH_TRANSLATION_LANGUAGES = ['BaniDB', 'manmohan singh', 'sant singh khalsa'];
export const HINDI_TRANSLATION_LANGUAGES = ['sahib singh', 'sant singh'];
export const STEEK_LANGUAGES = ['BaniDB', 'sahib singh', 'fareedkot', 'manmohan singh'];
export const TRANSLITERATION_LANGUAGES = ['english', 'hindi', 'shahmukhi', 'IPA'];
export const PUNJABI_LANGUAGE = 'punjabi';
export const ENGLISH_LANGUAGE = 'english';
export const HINDI_LANGUAGE = 'hindi';
export const SPANISH_LANGUAGE = 'spanish';